### ISSUE TITLE
嘗試採用更精確的物件命名方式

### ISSUE THREAD

**Issue by ronail** [seinsight-ac/sein-dashboard#204]
物件命名應以提示物件的Type, attributes和用途

Class name 應避免以Db結尾的物件，因為這樣意義上是指每一個物件都是一個database，但實際上並不是
建議以countable的詞語作suffix e.g. Metric

Database query 結果的variable 應該以眾數命名，而且盡量包含Class name，如`daily_fb_metrics = FbMetric.where(...)`

避免使用data命名變數，寧可以xxx_items，xxx_hash 可以簡單表達物件的Type和用途

**Comment by tsangyuwen** [comment]
先回答以DB結尾的部分，只要以Db結尾的，都是真正的資料庫
至於命名的部分，這次專案不會再針對命名去做修正，但以後我們code的時候會改進命名的部分
