### ISSUE TITLE
[Product Feedback] Flash 會被其他介面蓋住變得不明顯

### ISSUE THREAD

**Issue by dlackty** [seinsight-ac/sein-dashboard#213]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/14349/46573456-2408d180-c9c8-11e8-8b21-714dbb38be69.png">

如以上附圖，建議可以調整一下 Flash 設計，讓他可以更醒目一些。

**Comment by FunkyGary** [comment]
感謝，完形歐改
